## ------------------------- Messages ------------------------- ##

# You can use either & or § for colors
# To use player names use {player}
# To use command use {command}
# To use reason use {reason}

error-message-no-permission: "§cYou don't have permission to use this command!"
error-message-player-not-found: "§cPlayer not found!"
randomtp-success-message: "§aYou have been teleported to a random location!"
vanish-success-message: "§aYou have been vanished!"
unvanish-success-message: "§aYou have been unvanished!"
first-join-broadcast: "§a{player} has joined the server for the first time!"
first-join-message: "§aWelcome to the server!"
join-broadcast: "§7[§a+§7] §f{player}"
leave-broadcast: "§7[§c-§7] §f{player}"
unban-message: "§a{player} has been unbanned!"
player-not-banned: "§c{player} is not banned!"
error-message-no-args: "§cUsage {command}!"
ban-message: "§c{player} has been banned for {reason}!"
kick-message: "§cYou have been kicked for {reason}!"
error-message-no-player-for-ban: "&cIncorrect usage {command}"
error-message-ban-yourself: "§cYou can't ban yourself!"
error-message-no-reason-for-ban: "&cIncorrect usage {command}"
error-message-no-time-for-ban: "&cIncorrect usage {command}"
error-message-no-player-for-kick: "&cIncorrect usage {command}"
error-message-kick-yourself: "§cYou can't kick yourself!"
error-message-no-reason-for-kick: "&cIncorrect usage {command}"
error-message-no-player-for-mute: "&cIncorrect usage {command}"
error-message-no-reason-for-mute: "&cIncorrect usage {command}"
error-message-no-time-for-mute: "&cIncorrect usage {command}"
player-muted-message: "§cYou have muted {player}"
muted-message: "&cYou've been muted by {player} for {reason}"
player-is-muted: "§cYou are muted and cannot speak!"



## ------------------------- MOTD ------------------------- ##

motd: true

# To use player names use {player}

motd-message:
  - "§bWelcome to the server &e{player}!"
  - ""
  - "§7This is a test server!"
  - "§7Enjoy your stay!"

## ------------------------- Scoreboard ------------------------- ##
scoreboard: true
scoreboard-name: "§b§lTest Server"
scoreboard-text:
  - "§7This is a test server!"
  - "§7Enjoy your stay!"
  - ""
  - "§7Online: §a{online}"

## ------------------------- Spawn Coordinates ------------------------- ##

spawn:
  x: 0
  y: 0
  z: 0

## ------------------------- RTP Settings ------------------------- ##

# True = Will follow the value set in border as the max distance to tp
# False = Will teleport the player anywhere within 25,000 blocks
world-border: true

# How far to tp
border: 200

## ------------------------- Ban GUI ------------------------- ##
#Example:
#GUI:
#    name: "§b§lBan GUI"
#    size: 27
#    cancel:
#        material: "BARRIER"
#        slot: 26
#    items:
#        1:
#           reason: "§c§lRacism"
#           type: "ban"
#           material: "REDSTONE_BLOCK"
#           slot: 0
#           length-of-punishment: "14D"
#        2:
#           reason: "§c§lSpamming"
#           type: "mute"
#           material: "OBSIDIAN"
#           slot: 1
#           length-of-punishment: "3D"
GUI:
  name: "§b§lBan GUI" # This will have player name afterwards
  size: 27
  cancel:
    material: "BARRIER"
    slot: 26
  items:
    1:
      reason: "§c§lGriefing"
      type: "ban"
      material: "RED_CONCRETE"
      slot: 0
      length-of-punishment: "7D"
    2:
      reason: "§c§lHacking"
      type: "ban"
      material: "RED_CONCRETE"
      slot: 9
      length-of-punishment: "7D"
    3:
      reason: "§c§lAdvertising"
      type: "ban"
      material: "RED_CONCRETE"
      slot: 18
      length-of-punishment: "7D"
    4:
      reason: "§c§lSpamming"
      type: "tempmute"
      material: "BLUE_CONCRETE"
      slot: 1
      length-of-punishment: "3D"
    5:
      reason: "§c§lRacism"
      type: "tempmute"
      material: "BLUE_CONCRETE"
      slot: 10
      length-of-punishment: "7D"
    6:
      reason: "§c§lHarassment"
      type: "tempmute"
      material: "BLUE_CONCRETE"
      slot: 19
      length-of-punishment: "7D"
    7:
      reason: "§c§lAnnoying"
      type: "kick"
      material: "YELLOW_CONCRETE"
      slot: 2
      length-of-punishment: "Irrelevant"
    8:
        reason: "§c§lJust Because"
        type: "ban"
        material: "YELLOW_CONCRETE"
        slot: 11
        length-of-punishment: "7D"


## ------------------------- Ban Screen ------------------------- ##
BanMessage: "§cYou have been banned! \n§cReason: {reason} \n§cLength of ban: {length}\n §cAppeal at: https://itzsimplyjoe.me \n§cIf you believe this is a mistake, contact an admin."

