## ------------------------- Messages -------------------------

error-message-no-permission: "&cYou don't have permission to use this command!"
error-message-player-not-found: "&cPlayer not found!"
spawn:
  x: 0
  y: 0
  z: 0

world-border: true #True if limit how far to tp
border: 200 #How far to tp


