name: Firstplugin
version: '1.0-SNAPSHOT'
main: me.itzsimplyjoe.firstplugin.Firstplugin
api-version: 1.19
authors: [ItzSimplyJoe]
description: My First Plugin
website: https://itzsimplyjoe.me
commands:
  c:
    description: puts the user into creative mode
    usage: /<command>
    aliases:
      - creative
      - gmc
  a:
    description: puts the user into adventure mode
    usage: /<command>
    aliases:
      - adventure
      - gma
  s:
    description: puts the user into survival mode
    usage: /<command>
    aliases:
      - survival
      - gms
      - surv
  sp:
    description: puts the user into spectator mode
    usage: /<command>
    aliases:
      - spectator
      - gmsp
  feed:
    description: sets the players hunger to full
    usage: /<command>
    aliases:
      - feedme
      - nomorehungryness
  god:
    description: makes the user invulnerable
    usage: /<command>
    aliases:
      - godmode
      - invincible
  setspawn:
    description: sets the spawn of the server
    usage: /<command>
    aliases:
      - setworldspawn
      - spawnset
  spawn:
    description: teleports the user to spawn
    usage: /<command>
  rtp:
    description: teleports the user to a random location
    usage: /<command>
    aliases:
      - randomtp
      - randomteleport
  vanish:
    description: makes the user invisible
    usage: /<command>
    aliases:
      - invis
      - invisible
      - sv
      - v
  sb:
    description: opens a scoreboard gui
    usage: /<command>
    aliases:
      - scoreboard
      - scoreboardmenu
      - scoreboardui
      - scoreboards
  punish:
    description: opens a punishment gui
    usage: /<command>
    aliases:
      - punishmenu
      - punishui
      - punish
      - punishes
      - banmenu
  unban:
    description: unbans a player
    usage: /<command>
    aliases:
      - pardon
      - pardonplayer
      - unbanplayer
  ban:
    description: bans a player
    usage: /<command>
    aliases:
      - banplayer
  tempban:
    description: tempbans a player
    usage: /<command>
    aliases:
      - tempbanplayer
  kick:
    description: kicks a player
    usage: /<command>
    aliases:
      - kickplayer